/*
This macro takes as input (for the event structure) the output of
run_simHYDRA_laser.C and sets the drift parameters, the magnetic field (by
default the glad field with a current of 1500 A, though it can be changed) and
the laser parameters.

Making use of the class R3BGTPCLaserGen the electron cloud generated by the
passage of the laser is simulated and saved as a set ProjPoints.
*/

void run_laser_gen(Bool_t constB = kFALSE)
{

    TStopwatch timer;
    timer.Start();

    // Input file: simulation
    TString inFile = "../sim/Prototype/sim.root";
    // Input file: parameters
    TString parFile = "../sim/Prototype/par.root";
    // Output file
    TString outFile = "./Prototype/laser_gen";

    // Parameters
    TString GTPCGeoParamsFile;
    TString workDir = gSystem->Getenv("VMCWORKDIR");
    GTPCGeoParamsFile = workDir + "/glad-tpc/params/HYDRAprototype_FileSetup_v2_02082022.par";

    // -----   Create analysis run   ----------------------------------------
    FairRunAna* fRun = new FairRunAna();

    // ----------------- Magnetic Field Implementation -------------------------

    /*
    In this part the magnetic field is set. By default it's set to be a Glad field
    with a current of 1500 A (scale = current / 3583.81). However, it's possible
    to set a constant magnetic field running this macro as root -l
    'run_laser_gen(kTRUE)'
    */

    FairField* magField = NULL;

    if (constB)
    {
        magField = new R3BFieldConst();
        double B_y = 100.; //[kG]
        ((R3BFieldConst*)magField)->SetField(0., B_y, 0.);
        ((R3BFieldConst*)magField)
            ->SetFieldRegion(-200.0, // x_min
                             200.0,  // x_max
                             -100.0, // y_min
                             100.0,  // y_max
                             -150.0, // z_min
                             450.0); // z_max

        outFile += "_constField.root";
    }
    else
    {
        magField = new R3BGladFieldMap("R3BGladMap");
        ((R3BGladFieldMap*)(magField))->SetScale(0.4185489744);
        ((R3BGladFieldMap*)(magField))->Init();

        outFile += "_gladField.root";
    }

    fRun->SetField(magField);
    fRun->SetSource(new FairFileSource(inFile));
    fRun->SetOutputFile(outFile.Data());

    // -----   Runtime database   ---------------------------------------------
    FairRuntimeDb* rtdb = fRun->GetRuntimeDb();
    FairParRootFileIo* parIn = new FairParRootFileIo(kTRUE);
    FairParAsciiFileIo* parIo1 = new FairParAsciiFileIo(); // Ascii file
    parIo1->open(GTPCGeoParamsFile, "in");
    parIn->open(parFile.Data());
    rtdb->setFirstInput(parIn);
    rtdb->setSecondInput(parIo1);
    rtdb->print();

    // -------------- Laser Generation -----------------------------------------
    R3BGTPCLaserGen* lasergen = new R3BGTPCLaserGen();

    // lasergen->SetLaserParameters(alpha, beta, XIn, YIn, ZIn, maxLenght);
    // lasergen->SetLaserParameters(30, 50., 0., 16.204, 5.76, 50);
    // lasergen->SetLaserParameters(9.71, 1.54, 0., 16.204, 5.76, 500);
    lasergen->SetLaserParameters(11.67, 1.36, 0., 24.312, 6.98, 500);

    lasergen->SetNumberOfGeneratedElectrons(10000);

    // lasergen->SetProjPointsAsOutput();

    fRun->AddTask(lasergen);
    fRun->Init();
    fRun->Run(0, 0);
    delete fRun;

    timer.Stop();

    cout << "Macro finished succesfully!" << endl;
    cout << "Output file writen: " << outFile << endl;
    cout << "Parameter file writen: " << parFile << endl;
    cout << "Real time: " << timer.RealTime() << "s, CPU time: " << timer.CpuTime() << "s" << endl;
}
